#!/bin/bash
set -e

echo 'PROJ_DATA=/srv/conda/envs/notebook/share/proj' >> ~/.Renviron
echo 'PROJ_LIB=/srv/conda/envs/notebook/share/proj' >> ~/.Renviron

fc-cache -fv

rm -f README.md apt.txt environment.yml postBuild